name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t oumaymaii/my-first-hubrepo:latest1 .
          docker push oumaymaii/my-first-hubrepo:latest1

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} -e scope=repository:oumaymaii/my-first-hubrepo:push

      - name: Push Docker image to Docker Hub
        run: docker push oumaymaii/my-first-hubrepo:latest1
